fix(WINDOW): provide typesafe mock for `WINDOW`
ng-web-apis/universal pull request #9
Opened 2021-02-16 12:41 UTC by waterplea

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Closes #7

## What is the new behavior?

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Other information

2021-02-16 12:41 UTC, waterplea commented
Right now universal window relies on other universal tokens to be added. Need to reconsider that and write tests.

2021-02-18 08:23 UTC, MarsiBarsi requested changes

2021-02-18 08:23 UTC, MarsiBarsi commented on README.md
> +-   `WINDOW` — add `UNIVERSAL_WINDOW` to provide type-safe mock object, effectively mocking all `navigator` related entities
let's add a sample of how to provide UNIVERSAL_WINDOW and add a reference to it here. And some with brief description of use cases

2021-03-05 16:04 UTC, MarsiBarsi approved these changes

2021-03-05 16:04 UTC, merged